version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      TENANCY_MODE: ${TENANCY_MODE:-row}
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
  ai:
    image: python:3.11-slim
    command: ["python", "-m", "http.server", "8001"]
    ports:
      - "8001:8001"
volumes:
  pgdata:
